version: '3'
services:
  nginx:
    build: "nginx/."
    ports:        
        - 80:80     
    restart: always

  app1:
    depends_on:
      - nginx
    build: "app1/."
    restart: always

  app2:
    depends_on:
      - nginx
    build: "app2/."
    restart: always